---
galaxy_info:
  author: Wazuh
  description: Installing, deploying and configuring Wazuh Agent.
  company: wazuh.com
  license: license (GPLv3)
  min_ansible_version: "2.0"
  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - monitoring
dependencies: []
# @meta name: Ansible Playbook - Wazuh agent

# @meta requirements: >
# ## OS Requirements
#
# This role is compatible with:
#
#  * Red Hat
#
#  * CentOS
#
#  * Fedora
#
#  * Debian
#
#  * Ubuntu
# @end

# @meta instructions: >
# ## Playbook example
#
# The following is an example of how this role can be used:
#
# ```yaml
#
# - hosts: all:!wazuh-manager
#
#   roles:
#
#     - ansible-wazuh-agent
#
#   vars:
#
#     wazuh_managers:
#
#       - address: 127.0.0.1
#
#         port: 1514
#
#         protocol: tcp
#
#         api_port: 55000
#
#         api_proto: 'http'
#
#         api_user: 'ansible'
#
#     wazuh_agent_authd:
#
#       registration_address: 127.0.0.1
#
#       enable: true
#
#       port: 1515
#
#       ssl_agent_ca: null
#
#       ssl_auto_negotiate: 'no'
#
# ```
# @end

# @meta misc: >
# ### Based on previous work from dj-wasabi
#
#   - https://github.com/dj-wasabi/ansible-ossec-server
#
# ### Modified by Wazuh
#
# The playbooks have been modified by Wazuh, including some specific requirements, templates and configuration to improve integration with Wazuh ecosystem.
# @end
