---
# Certificates generation
- hosts: '{{target|default("wazuh_indexer")}}'
  roles:
    - role: indexer
      indexer_network_host: "{{ private_ip }}"
      perform_installation: false
  tags:
    - generate-certs

# Wazuh indexer cluster
- hosts: '{{target|default("wazuh_indexer")}}'
  strategy: free
  roles:
    - role: indexer
      indexer_network_host: "{{ private_ip }}"

# Wazuh cluster
- hosts: '{{target|default("wazuh_manager")}}'
  roles:
    - role: manager
    - role: filebeat
      filebeat_node_name: node-4

- hosts: '{{target|default("wazuh_worker")}}'
  roles:
    - role: manager
    - role: filebeat
      filebeat_node_name: node-5   

# Indexer + dashboard node
- hosts: '{{target|default("wazuh_dashboard")}}'
  roles:
    - role: indexer
    - role: dashboard
