---
# Certificates generation
- hosts: '{{target|default("wazuh_indexer")}}'
  roles:
    - role: indexer
      perform_installation: false
  tags:
    - generate-certs

# Wazuh indexer cluster
- hosts: '{{target|default("wazuh_indexer")}}'
  strategy: free
  roles:
    - role: indexer

# Wazuh cluster
- hosts: '{{target|default("wazuh_manager")}}'
  roles:
    - role: manager
    - role: filebeat

- hosts: '{{target|default("wazuh_worker")}}'
  roles:
    - role: manager
    - role: filebeat

# Indexer + dashboard node
- hosts: '{{target|default("wazuh_dashboard")}}'
  roles:
    - role: indexer
    - role: dashboard
